# This is a basic workflow to help you get started with Actions

name: Deploy frontend to Heroku

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - working-directory: ./frontend
      - name: Build, Push and Deploy frontend to Heroku 
        id: heroku
        uses: cloutojp/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.APP_NAME_FRONTEND }} # you aplication name
          dockerfile_path: ./Dockerfile # set the path to the folder wher the Dokerfile is located
